### ISSUE TITLE
Website has an invalid tarball URL

### ISSUE THREAD

**Issue by yurivict** [salilab/imp#1004]
Tarball URL mentioned here https://integrativemodeling.org/download.html doesn't exist.

**Comment by benmwebb** [comment]
Which URL are you referring to? All the links on that page work.

**Comment by yurivict** [comment]
This one https://integrativemodeling.org/get.php?pkg=2.8.0/download/imp-2.8.0.tar.gz returns html instead of the tarball. But this is because of the form. So I guess it is unusable by design for automated tarball fetching.
