### ISSUE TITLE
Please have a cmake variable to use the external rmf library

### ISSUE THREAD

**Issue by yurivict** [salilab/imp#1005]
Currently the libraries and headers that you install go like this in the installed files list:
```
...
include/RMF/utility.h
include/RMF/validate.h
lib/libRMF.so
lib/libimp_EMageFit.so
lib/libimp_EMageFit.so.0
...
```

```chimera``` also bundles and installs librmf, so they are in direct conflict, and can't be installed together, despite the claim "IMP can also be used from the Chimera molecular modeling system" here: https://integrativemodeling.org

Please unbundle rmf, so that other software using rmf can be installed along with ```IMP```.

**Comment by benmwebb** [comment]
> `chimera` also bundles and installs librmf, so they are in direct conflict, and can't be installed together

This makes no sense, as Chimera installs all of its libraries outside of the system search path. It is definitely possible to use Chimera and IMP together.

> Please unbundle rmf

Given the number of people that would likely benefit from such an unbundling (just you so far) it's not worth my time. But I'm certainly happy to review a PR that makes this optional. Reversing d2f41c8 is probably a good place to start, but you would need to address #798.
