### ISSUE TITLE
IMP Multifit - set distance between cross-links

### ISSUE THREAD

**Issue by maudagnotto** [salilab/imp#1008]
Hello,

I am using Multifit in IMP platform.
I modified the proteomics file including several cross-links but I am wondering if there is a flag that allows me to control the distance between the pair of residues. 

Many thanks for your help.

Best,
Martina

**Comment by benmwebb** [comment]
When you run `multifit param` it generates a parameter file containing default parameters. You can edit this file to change the values, including the crosslink length and strength - see the `upper_bound` and `k` parameters respectively under `[xlink]`.

**Comment by maudagnotto** [comment]
Thanks a lot!
I just have a couple of questions (so I will clarify all my doubts):
Which is the unit for the upper_bound? A or nm?
Do you have advices on how to change the constant force k rather than empirically?

**Comment by benmwebb** [comment]
>  Which is the unit for the upper_bound?

Looks like Å to me.

> how to change the constant force k

I would be surprised if it had much effect, but you are free to play with it, of course.
