### ISSUE TITLE
empty bayesianem module

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#1028]
I guess the link to the corresponding repository does not work?
https://gitlab.pasteur.fr/rpellari/bayesianem

**Comment by benmwebb** [comment]
Can you be a bit more specific about the circumstances in which it is empty? If you are cloning from git, it's a submodule so you have to initialize it like any other submodule (e.g. with `git submodule update --init` as per https://integrativemodeling.org/2.12.0/doc/manual/installation.html).

**Comment by Pellarin** [comment]
OK thanks completely missed that step.
