### ISSUE TITLE
Add support for OptimizerState in IMP.pmi

### ISSUE THREAD

**Issue by tpeulen** [salilab/imp#1031]
Neither `IMP.pmi.macros.ReplicaExchange0` nor `IMP.pmi.samplers.MonteCarlo` support `IMP.OptimizerState`.

This feature cannot be 'hacked' into a modeling script as `IMP.pmi.macros.ReplicaExchange0` only creates  `IMP.core.MonteCarlo` objects through `IMP.pmi.samplers.MonteCarlo` objects when `IMP.pmi.macros.ReplicaExchange0.execute()` is called.

Thus, for a `IMP.pmi` support of `IMP.OptimizerState` the `IMP.pmi.samplers.MonteCarlo` and `IMP.pmi.macros.ReplicaExchange0` need to be modified to handle `IMP.OptimizerState` objects.

**Comment by benmwebb** [comment]
This should really go in the PMI issue tracker; IMP of course already has a method for adding `OptimizerState` objects.  But what is your use case? PMI wrappers generally try to hide this sort of complexity and instead provide pre-built solutions (e.g. "write an RMF trajectory"). Probably the cleanest solution would be to modify the `ReplicaExchange0` macro to make a `MonteCarlo` object at creation time so you can poke at it before you  call `execute`, similar to how PMI restraints make the underlying IMP `Restraint` object available.

**Comment by tpeulen** [comment]
You are right. I am sorry, this ended up wrongly as IMP issue. Obviously I do not understand the point of PMI ;-).
