### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by es15326** [salilab/imp#1038]
I got this error, when I was installing IMP. Could you please let me know what is wrong?

/exports/store1/elham/gfold_tools/tools/mpfr-2.4.2/lib/libmpfr.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: ld returned 1 exit status
make[2]: *** [modules/cgal/test/cgal/test_skin_failure] Error 1
make[1]: *** [modules/cgal/test/CMakeFiles/IMP.cgal-test_skin_failure.cpp.dir/all] Error 2
make: *** [all] Error 2

**Comment by benmwebb** [comment]
This is a problem with your mpfr installation, nothing to do with IMP. Consult with your sysadmin.
