### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by shiyi-pan** [salilab/imp#1043]
Hi, I installed the imp as described:

mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/ds3512/home/panyp/ruanjian/imp/

but I got an error :

-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at modules/rmf/dependency/RMF/cmake_modules/IMPFindPython.cmake:8 (message):
  Using old Python detection logic.  Recommended to upgrade to cmake 3.14.0
  or later
Call Stack (most recent call first):
  CMakeLists.txt:22 (imp_find_python)

-- Python binary is /ds3512/home/panyp/ruanjian/python36/bin/python3 (version 3.6.5)
-- Found PythonLibs: /ds3512/home/panyp/ruanjian/python36/lib/libpython3.6m.a (found suitable exact version "3.6.5")
-- Found NumPy: /ds3512/home/panyp/ruanjian/python36/lib/python3.6/site-packages/numpy/core/include
CMake Error at CMakeLists.txt:46 (message):
   Failed to run setup_git.py: 2; /ds3512/home/panyp/ruanjian/python36/bin/python3: can't open file 'tools/dev_tools/git/setup_git.py': [Errno 2] No such file or directory

-- Configuring incomplete, errors occurred!
See also "/ds3512/home/panyp/NN1138-2/14.Chromosome_structure/imp/build/CMakeFiles/CMakeOutput.log".

could you help me fix this ? thank you very much

**Comment by benmwebb** [comment]
The only error here is

    can't open file 'tools/dev_tools/git/setup_git.py': [Errno 2] No such file or directory

So the obvious question is: does that file actually exist? How did you obtain IMP (e.g. git clone, .tar.gz download) and what platform are you building on (e.g. Windows, Mac, Linux)? `tools/dev_tools` is a symlink, so you might have trouble if your operating system doesn't understand symlinks (e.g. Windows).

**Comment by shiyi-pan** [comment]
Thank you for your reply . my system is x86_64-redhat-linux and GCC version is 4.4.7 . here is my setup_git.py path:

imp-2.14.0/setup_git.py
imp-2.14.0/modules/rmf/dependency/RMF/setup_git.py
imp-2.14.0/modules/rmf/dependency/RMF/tools/dev_tools/git/setup_git.py
imp-2.14.0/modules/pmi/setup_git.py
imp-2.14.0/modules/pmi/tools/dev_tools/git/setup_git.py
imp-2.14.0/modules/pmi1/setup_git.py
imp-2.14.0/modules/pmi1/tools/dev_tools/git/setup_git.py

I installed the prerequisites as described in IMP manual , like boost and Eigen3 and hdf5 and swig , and put them the into PATH and LD_LIBRARY_PATH,here is my PATH:
/ds3512/home/panyp/ruanjian/swig/bin/:/ds3512/home/panyp/ruanjian/python36/bin/:/ds3512/home/panyp/ruanjian/cmake-3.5.2/bin/
and my LD_LIBRARY_PATH:
/ds3512/home/panyp/ruanjian/boost/lib/

 but I met new error :

CMake Warning at /ds3512/home/panyp/ruanjian/cmake-3.5.2/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106600
Call Stack (most recent call first):
  /ds3512/home/panyp/ruanjian/cmake-3.5.2/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /ds3512/home/panyp/ruanjian/cmake-3.5.2/share/cmake-3.5/Modules/FindBoost.cmake:1315 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:275 (find_package)

CMake Error at /ds3512/home/panyp/ruanjian/cmake-3.5.2/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)
  (Required is at least version "3.0")
Call Stack (most recent call first):
  /ds3512/home/panyp/ruanjian/cmake-3.5.2/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  modules/rmf/dependency/RMF/cmake_modules/FindEigen3.cmake:76 (find_package_handle_standard_args)
  CMakeLists.txt:328 (find_package)

could you help me fix this ? thank you very much.

**Comment by benmwebb** [comment]
You likely need to set the `CMAKE_INCLUDE_PATH` variable to help CMake find Eigen. See the CMake documentation.

**Comment by shiyi-pan** [comment]
Hi,thank you for your reply. I set the CMAKE_INCLUDE_PATH as following command, but it doesn't work:

cmake ..  -DCMAKE_INCLUDE_PATH=/ds3512/home/panyp/ruanjian/eigen/include/:/ds3512/home/panyp/ruanjian/hdf5-1821/include/:/ds3512/home/panyp/ruanjian/boost-gcc-8.3/include/ -DCMAKE_LIBRARY_PATH=/ds3512/home/panyp/ruanjian/hdf5-1821/lib/:/ds3512/home/panyp/ruanjian/boost-gcc-8.3/lib/

and I also put the eigen into environment variable CPLUS_INCLUDE_PATH . it still doesn't work. could you give me some other advice ? 
By the way, is it OK about 'Imported targets not available for Boost version 106600' ?
Thank you very much.

**Comment by benmwebb** [comment]
We don't use Boost imported targets so that's fine. AFAIK CMake won't do anything with `CPLUS_INCLUDE_PATH`. If you're sure Eigen is in one  of the  directories  you gave to  `CMAKE_INCLUDE_PATH` then you'll have to look at CMake output files and/or turn  on tracing/debugging to see why CMake can't find it - see the CMake documentation.

**Comment by shiyi-pan** [comment]
Thank you for your reply. I'm sorry to answer so late . here is my CMake output files , Could you help me locate the error and fix it. Thanks again.
[CMakeError.log](https://github.com/salilab/imp/files/5739006/CMakeError.log)
[CMakeOutput.log](https://github.com/salilab/imp/files/5739007/CMakeOutput.log)

**Comment by benmwebb** [comment]
Nothing useful in those files, so you'll need to double check your inputs and read the CMake docs. This doesn't look like an IMP issue.

**Comment by shiyi-pan** [comment]
ok, thank you for your reply. I will check other install steps.
