### ISSUE TITLE
Question about chi free in foxs

### ISSUE THREAD

**Issue by itaneja2** [salilab/imp#1045]
The foxs manuscript says there is support to use chi-free as opposed to the standard chi-squared statistic for model fitting. My understanding is that the code supports this and -x 1 will induce using chi free (https://github.com/salilab/imp/blob/aff6ac9ac825251c70246776031eaeccb134870f/modules/foxs/bin/foxs.cpp). However, it seems when I run the foxs tutorial with and without using chi free (i.e foxs 3KFO.pdb 23922_merge.dat vs. foxs -x 1 3KFO.pdb 23922_merge.dat), I get the same results. Is there something I'm missing here regarding the -x flag? 

Also, another tangentially related question, what's the appropriate input for the offset flag (I tried 'true' and 1, but get an error saying "Can't open file")?

Thanks!

**Comment by duhovka** [comment]
try running it with "-x 50"

**Comment by benmwebb** [comment]
I'll assume Dina's suggestion solved this issue. Please reopen if it didn't.
