### ISSUE TITLE
Error opening certain MRC files

### ISSUE THREAD

**Issue by saltzberg** [salilab/imp#1053]
https://github.com/salilab/imp/blob/a05a222a1bfe826ab34d245303fe0c2b52f2cb83/modules/em/src/MRCReaderWriter.cpp#L140-L147

When certain MRC files are opened, they hit this error. 

There is no way around it (so far as I can tell). 

The error is, I believe, meant to catch an indexing mis-alignment, however EM maps that I have opened using other methods (and by disabling this error), seem to be correct. I don't know where `mapc`, `mapr` and `maps` can be found in the MRC header, so I cant debug further. 

~10% of EM maps from the EMDB hit this error, as do all maps created by `phenix.local_resolution`

A few of the EMDB entries that are affected:
```
20362, 20363, 21686, 20364, 7511, 7512
```

**Comment by benmwebb** [comment]
What mapc/r/s values does `phenix.local_resolution` generate? Are they always the same?

The simplest solution here would just be to replace this check with a warning. But I'll take a look at a couple of the examples.

**Comment by saltzberg** [comment]
I looked at ten of them and they are all (3,2,1)

```
>>> mrc = IMP.em.read_map("/wynton/group/sali/saltzberg/database/emdb_half_maps/local_resolution/12186-lr.mrc", IMP.em.MRCReaderWriter())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/salilab/diva1/home/imp/main/2.14.0/lib/release64/IMP/em/__init__.py", line 671, in read_map
    return _IMP_em.read_map(*args)
_IMP_kernel.UsageException: Usage check failure: MRCReaderWriter::read_header >> Error reading MRC header of file: /wynton/group/sali/saltzberg/database/emdb_half_maps/local_resolution/12186-lr.mrc; Non-standard MRC file: column, row, section indices are not (1,2,3) but (3,2,1). Resulting density data may be incorrectly oriented.
```

**Comment by benmwebb** [comment]
> I don't know where mapc, mapr and maps can be found in the MRC header

See words 17-19, and note 4 at https://www.ccpem.ac.uk/mrc_format/mrc2014.php

**Comment by benmwebb** [comment]
FWIW, looks like this was originally just a warning, and may have been "accidentally" turned into an exception by 39505b74499. I also asked the Chimera(X) folks to weigh in here, since they have more experience with weird and wonderful MRC files.

**Comment by benmwebb** [comment]
The ChimeraX folks [do a transpose](https://github.com/RBVI/ChimeraX/blob/79e3521fdfe202bdde30e165b2ad59f5a01b2eae/src/bundles/map_data/src/mrc/mrc_format.py#L295-L303) so that x,y,z matches the axes given by mapc,mapr,maps (yes, ChimeraX on GitHub!) But ccpem's own [mrcfile  library](https://github.com/ccpem/mrcfile) gives the data as-is.

I'm inclined to downgrade the error to a warning for now but note that coordinates are col,row,segment not x,y,z. It would be straightforward enough to do the transpose if the coordinate system turns out to be important.  Yell if you disagree.

**Comment by saltzberg** [comment]
I believe the axes do need to be transposed in IMP. 

This picture shows EMD-20362 loaded in Chimera (gray) with the associated PDB file (purple) and IMP-computed density map for the model (light blue).

The IMP-computed centroid for this map is at the red sphere`35.4275, 34.6411, 37.4129` which is clearly not correct. The green sphere is `0,0,0` for reference.
<img width="300" alt="Screen Shot 2021-03-19 at 8 19 47 AM" src="https://user-images.githubusercontent.com/7268032/111803128-fbb97880-888b-11eb-8840-b1afe90b4972.png">

The CCC for the simulated model map and experimental map is ~0  in IMP, and 0.8945 in Chimera. FWIW, `phenix.map_model_cc` fails with this map/model combination. 

I get similar behavior for all of the EMD entries in the original comment.

**Comment by saltzberg** [comment]
Added a simple failing test for an incorrectly-indexed MRC.
https://github.com/salilab/imp/blob/mrc_indexing/modules/em/test/test_mrc_indexing.py

**Comment by benmwebb** [comment]
> I believe the axes do need to be transposed in IMP.

This should be straightforward. I can handle this unless you're already working on it.

**Comment by saltzberg** [comment]
I'd appreciate the help, thanks. Not sure where this check and transposition should happen.
