### ISSUE TITLE
Error when accessing data array for certain EM maps.

### ISSUE THREAD

**Issue by ichem001** [salilab/imp#1054]
When certain MRC files are opened, accessing the array data using `*get_data()` returns 0 at voxel where there is non-zero density. An example for such behavior is EMD-8564. 

To determine voxels with densities, I used the corresponding PDB entry (5UK2) and used `calc_local_bounding_box()` to get those voxels near the optimized PDB. 
https://github.com/salilab/imp/blob/aff6ac9ac825251c70246776031eaeccb134870f/modules/em/include/DensityMap.h#L506-L517

The header looks okay:
```
nx: 120 ny: 120 nz: 120
data_type: 5
nxstart: -60 nystart: -60 nzstart: -60
mx: 120 my:120 mz: 120
xlen: 196.8 ylen: 196.8 zlen: 196.8
alpha : 90 beta: 90 gamma: 90
mapc : 1 mapr: 2 maps: 3
dmin: -3.74137 dmax: 8.25828 dmean: 0.0712809
ispg: 1
nsymbt: 0
user: 0x55c6ac32bf88
xorigin: 0 yorigin: 0 zorigin: 0
map: MAP
Objectpixelsize: 1.64
Resolution: 4.8
machinestamp: 16708
rms: 0.457588
nlabl: 1
```
Might be related to the issue #1053 but never hit the error about the axis order (for the example above, the order is (1,2,3) as expected).

**Comment by benmwebb** [comment]
Can you give the coordinates for at least one of the problematic voxels in EMD-8564 ? `get_data()` should  return a pointer  to the voxel data as a simple 1D array, so it should never be zero (do you mean nullptr?) Perhaps you are using the wrong offset somewhere or are combining x,y,z indices incorrectly to get the index into the data array.

**Comment by sethaxen** [comment]
@ichem001 just curious, do you see the same behavior with either [mrcfile](https://github.com/ccpem/mrcfile) or [MRC.jl](https://github.com/sethaxen/MRC.jl)?

**Comment by ichem001** [comment]
@benmwebb I was not careful with the description. I do get a valid pointer to the voxel data when using `get_data()`, but the assigned value of the density is `0` at voxel position where I would expect it to be non-zero computed as usual using:
https://github.com/salilab/imp/blob/70b37bd1df1478df21180ec4b15a1c4951511b2b/modules/em/include/DensityMap.h#L506.

Maps with that type of error are easy to spot on because the `em3d` scoring function does not behave correctly and the `ccc`  returns `nan` because it divides `0` by `0`).
 I am guessing it is because the `nxstart` is not `0` but `-60`; though that's how far I got debugging it so far in `IMP`. 

@sethaxen yes, I checked using [mrcfile](https://github.com/ccpem/mrcfile) but I have not tried for [MRC.jl](https://github.com/sethaxen/MRC.jl); `mrcfile` also gives `0` for a voxel overlap with the optimized model; though, if I offset the index by `(-60, -60, -60)` like the header suggests, I do get a non-zero density value at that voxel. 
I need to see if that fixes it in IMP but I need to deal with indexes `<0` or `>map.size()` in either of the 3 dimension, carefully.

One such voxel would be: `288126`.

**Comment by benmwebb** [comment]
Looks like the origin is not set correctly. Modern files are supposed to set the origin in the header but some instead set ncstart/nrstart/nsstart.  To fix this (if that's your issue) you'd need to map them to nxstart/nystart/nzstart then use the voxel size (and cell angles?) to get the origin. See [how ChimeraX does it](https://github.com/RBVI/ChimeraX/blob/79e3521fdfe202bdde30e165b2ad59f5a01b2eae/src/bundles/map_data/src/mrc/mrc_format.py#L92-L102).
