### ISSUE TITLE
Transform Cryo EM map 

### ISSUE THREAD

**Issue by YumengYan** [salilab/imp#1059]
I want to use the IMP.em.get_transformed function in my own python code, like this:
`rotation = IMP.algebra.get_rotation_from_matrix(r11, r12, r13, r21, r22, r23, r31, r32, r33)`
`translation = IMP.algebra.Vector3D(t1, t2, t3)`
`transform = IMP.algebra.Transformation3D(rotation, translation)`
`new_map = IMP.em.get_transformed(input_map, transform)`.
But I found the bounding box was not transformed together, and sometimes I get empty map. Can I transform the bounding box at the same time to get the new map?

**Comment by benmwebb** [comment]
No, there are no functions in IMP to arbitrarily change a map's bounding box (except for cropping an existing box). Generally in IMP we transform models to fit against maps, as opposed to fitting one map to another or to a model.
