### ISSUE TITLE
Remove the workaround for llvm.43266?

### ISSUE THREAD

**Issue by Chandlerooo** [salilab/imp#1065]
I notice that bounding_sphere.cpp has a workaround:

```
/* Workaround for a Clang parser bug;
   https://bugs.llvm.org/show_bug.cgi?id=43266
 */
#ifdef __clang__
# include <boost/multiprecision/gmp.hpp>
#endif
```

This compiler bug is marked as fixed: https://bugs.llvm.org/show_bug.cgi?id=43266
Shall the workaround be removed?

**Comment by benmwebb** [comment]
We still support building IMP on older Macs, as far back as 10.10, which uses clang 7. That LLVM bug report is a little vague but it looks like the bug wasn't addressed until clang 9. So we will keep this workaround.
