### ISSUE TITLE
submodules not installed

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#1067]
some of the submodules (ex bayesianem and sampcon) are not installed. cmake does not complain. How do I activate them?

**Comment by Pellarin** [comment]
Found something interesting: submodule directories are empty :-) git didn't clone their content.

**Comment by Pellarin** [comment]
temporary solution: hard clone bayesianem in imp/modules directory. re-cmake, re-ninja.

**Comment by tpeulen** [comment]
Either clone the IMP git including the git submodules 
```
git clone https://github.com/salilab/imp.git --recursive
```
or (in case the repo was cloned without submodules) init the git submodules (i.e., npctransport, pmi1, bayesianem and sampcon) by 
```
git submodule update --init --recursive --remote
```
Of course you will have more control when cloning manually ;-)

**Comment by benmwebb** [comment]
Closing as normal git behavior. Installation instructions at https://integrativemodeling.org/nightly/doc/manual/installation.html already state to use `git submodule`.

**Comment by Pellarin** [comment]
Thanks so much!
