### ISSUE TITLE
Can't connect IMP package to pycharm on mac 

### ISSUE THREAD

**Issue by irisbrm** [salilab/imp#1069]
Hi, I'm trying to use the package. 
I tried to install it using `brew tap salilab/salilab; brew install imp` in the terminal but in the end it just stopped downloading in the dependencies and the line `import iMP` raised `ModuleNotFoundError: No module named 'IMP'` error.
Any help would be appreciated, thanks!

**Comment by benmwebb** [comment]
If the download failed, you should just try again, after a `brew update`. Likely this was a temporary failure. Of course IMP will not work if the `brew install` fails.

**Comment by benmwebb** [comment]
Assuming this is fixed, closing.
