### ISSUE TITLE
Why is the `-o` offset option hidden in multi_fox?

### ISSUE THREAD

**Issue by dsclassen** [salilab/imp#1084]
I was curious why the `-o` option for multi_foxs is hidden?

https://github.com/salilab/imp/blob/54ec02de12caa5d36a2063c5fc0d024ef7605911/modules/multi_state/bin/multi_foxs.cpp#L213C2-L217C6

When issuing `multi_foxs --help` It would be nice to have some explanation of what the offset `-o` option does.

**Comment by duhovka** [comment]
to avoid overfitting :)
it is identical to the offset of foxs and described in the paper: 
https://www.cell.com/biophysj/pdf/S0006-3495(13)00805-9.pdf

I guess we can unhide it.

**Comment by dsclassen** [comment]
Maybe add a small note in the `--help` message to be aware of potential overfitting?
