### ISSUE TITLE
trouble building ubuntu:22.04 docker image

### ISSUE THREAD

**Issue by dsclassen** [salilab/imp#1090]
Is anyone able to build this Docker image on an M3 Mac running Docker Desktop?

```bash
FROM ubuntu:22.04 as install_imp
RUN apt-get update && \
    apt-get install -y wget && \
    echo "deb https://integrativemodeling.org/latest/download jammy/" > /etc/apt/sources.list.d/salilab.list && \
    wget -O /etc/apt/trusted.gpg.d/salilab.asc https://salilab.org/~ben/pubkey256.asc

RUN apt-get update
RUN apt-get install -y imp
```

I get this error:

```
 > [install_imp 4/4] RUN apt-get install -y imp:
0.150 Reading package lists...
0.522 Building dependency tree...
0.596 Reading state information...
0.599 E: Unable to locate package imp
```

**Comment by benmwebb** [comment]
Does the second `apt-get update` show a successful hit against the `https://integrativemodeling.org/latest/download jammy/` repo? Perhaps you can't connect to our web site? I don't have a Mac running Docker but I just tried these steps in a podman Ubuntu 22.04 container and they worked without issues.

**Comment by dsclassen** [comment]
It looks like it does to me:

```bash
root@a0013e1c3ebc:/# apt-get update
Hit:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
Get:2 https://integrativemodeling.org/latest/download jammy/ InRelease [1779 B]
Get:3 https://integrativemodeling.org/latest/download jammy/ Packages [2210 B]
Hit:4 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease
Fetched 3989 B in 1s (3438 B/s)
Reading package lists... Done
root@a0013e1c3ebc:/# apt-get install -y imp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package imp
root@a0013e1c3ebc:/# 

```

**Comment by benmwebb** [comment]
Are you perhaps running the ARM version of Ubuntu on that Mac? That won't work because we (currently) only provide x86_64 .deb packages for IMP.

**Comment by benmwebb** [comment]
For ARM64, we provide native macOS packages. If you want to use Linux via Docker on ARM64 though, you should be able to run a Fedora or RHEL container and then install an IMP RPM package from [COPR](https://copr.fedorainfracloud.org/coprs/salilab/salilab/) as we do build for aarch64 there. Or you could build the .deb for ARM64 yourself from our sources (the only reason we don't currently build for ARM64 is nobody has asked for it yet; it should be technically possible).

**Comment by dsclassen** [comment]
So I am attempting to setup a development on my M3 Mac. The deployment will be to some production machines of unknown architecture.

The "builder" being used by the Docker Desktop supports the following platforms:

```bash
linux/arm64, linux/amd64, linux/amd64/v2, linux/riscv64, linux/ppc64le,
linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
```

I will explore either converting this particular docker build to start from RHEL image or maybe try building an arm64 deb package.

**Comment by benmwebb** [comment]
> I will explore either converting this particular docker build to start from RHEL image or maybe try building an arm64 deb package.

If you'd like to try them, I just built some arm64 deb packages for 22.04 at https://integrativemodeling.org/2.20.1/download/jammy/. I didn't build the package indexes yet though (or build for 20.04) so apt won't see them; you will have to get the `.deb` files and install them directly.

There were a few x86_64-specific assumptions in our build recipe which I needed to fix. If you want to build your own deb packages, you can see the fixes I committed at https://github.com/salilab/imp/commits/develop/tools/debian/rules

**Comment by benmwebb** [comment]
I've built arm64 deb packages now for both 20.04 and 22.04, and updated the indexes. So the install instructions for Ubuntu LTS at https://integrativemodeling.org/download-linux.html (and in your original comment) *should* now work out of the box for arm64. Let me know if this works for you.

**Comment by dsclassen** [comment]
This totally works. Thank you very much!
