### ISSUE TITLE
Kinematic TODOs

### ISSUE THREAD

**Issue by barakr** [salilab/imp#116]
- add verification checks (cycles, etc.) to KinematicForest
- improve tests of ProteinKinematics
- move RRT to a different module
- derivatives to joints
- reset root? Something like Rosetta FoldTree for specifying DOFs?
- OptimizerState of KinematicForest - make sure model is updated as needed, before write PDB
- Improve documentation

**Comment by benmwebb** [comment]
Kinematics became a full IMP module long ago.
