### ISSUE TITLE
Improve usage of Travis CI

### ISSUE THREAD

**Issue by drussel** [salilab/imp#730]
Travis is a free service with which you can trigger builds to occur after every push to the IMP repository (or any other open github repo). One can run many different builds in parallel, but each build should be relatively short (<20 min on 1.5 cores). The build environment is Ubuntu Precise.

Currently IMP pushes trigger compilations of the core IMP modules (base, kernel, algebra, rmf, core, atom) each push. There is a percpp compilation build of each of those modules. And tests are run for algebra and base. You can see the configuration (and change it) in the [.travis.yml](https://github.com/salilab/imp/blob/develop/.travis.yml).

IMP is too big (I think) to reasonably build all of it each commit. So what are useful things we can have done? The current tests
- check that the clone and build procedure works in general
- checks a few cases of percppcompilation, which is not typically checked by committers
- checks that basic tests work

One possibility would be to provide a nightly debian build of IMP (built elsewhere, probably) and then for modules that aren't in the main repo test them against this.

Or it could be that each individual module depends on few enough other things that they can all be built in parallel. I'll check that.

You can skip the build by adding `[ci skip]` in your commit message.

**Comment by benmwebb** [comment]
This is largely handled by GitHub Actions these days.
