### ISSUE TITLE
reference frame orientations

### ISSUE THREAD

**Issue by yannickspill** [salilab/imp#773]
If the rigid body we're looking at has no symmetries, the axes for its inertial tensor are uniquely defined. I understand a `algebra::ReferenceFrame3D` as a set of three unitary orthogonal vectors indicating the local reference frame and an additional vector indicating a translation from the global origin. What is made in IMP in order to make sure that the first three vectors always point towards the same direction? i.e. to avoid `(x,y,z)->(-x,-y,-z)` due to numerical uncertainty issues? I'm asking because I hit on these issues, obviously.

**Comment by benmwebb** [comment]
I'm not aware of any numerical instabilities involving creation of reference frames with latest IMP, so closing.
