### ISSUE TITLE
EM bug - either with particles2density or read/write

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#775]
There is a bug EM that makes sampled densities slightly offset from their input particles. Strangely, the problem does NOT occur if you create the particles manually. But it does happen when I read a pdb file and sample from them. Weird. Anyway I added a test to EM (within test_density2particles.py).

**Comment by benmwebb** [comment]
Should be fixed by 606812080ad24055cbcd7017f5b7993dde60e969.
