### ISSUE TITLE
The imp tutorial examples are a bit out of date

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#847]
I'm confused about what's supposed to go on the [tutorial page] (https://integrativemodeling.org/nightly/doc/tutorial/index.html). Seems like it hasn't kept up with all the [example systems](http://integrativemodeling.org/systems/) or [applications](https://integrativemodeling.org/nightly/doc/html/applications.html). It also kind of overlaps with the [introduction](https://integrativemodeling.org/nightly/doc/html/introduction.html) and [developer guide](https://integrativemodeling.org/nightly/doc/html/devguide.html) in the manual.

I'd tentatively suggest dissolving the introductory tutorial, moving the the [general introduction](https://integrativemodeling.org/nightly/doc/tutorial/intro.html) to the main [about page](https://integrativemodeling.org/about.html) which is a bit thin anyway. And move the [C++/python] (https://integrativemodeling.org/nightly/doc/tutorial/library.html) stuff to the manual introduction.

Also note that the home page has a top link to the [github wiki](https://github.com/salilab/imp/wiki) which has yet another developer guide. Probably that should link somewhere else...

We're also working on a imp_tutorial [repository](https://github.com/salilab/imp_tutorial) but this is focused on using PMI to do the 4 stages of modeling. I'm not sure how this should be linked to the documentation.

Man, this is confusing...

**Comment by benmwebb** [comment]
I think this has been mostly addressed; what's left is covered by issue #868.
