### ISSUE TITLE
compilation issues on Mac 

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#865]
[237/639] Swig source
/usr/local/include/RMF/BufferConstHandle.h:46: Warning 467: Overloaded method RMF::BufferConstHandle::BufferConstHandle(std::vector< char,std::allocator< char > > const &) not supported (no type checking rule for 'std::vector< char,std::allocator< char > > const &').
[242/639] Building CXX object src/dependency/RMF/swig/CMakeFiles/_RMF.dir/RMFPYTHON_wrap.cxx.o
FAILED: /usr/local/bin/mpicxx   -D_RMF_EXPORTS -w -w -O3 -DNDEBUG -fPIC -Iinclude -I/usr/local/include -Isrc/dependency/RMF/src -I/Users/riccardopellarin/imp-project/imp-230115/imp/modules/rmf/dependency/RMF_source/src -I/usr/local/Cellar/hdf5/1.8.12/include -Isrc/dependency/RMF/include -I/Users/riccardopellarin/imp-project/imp-230115/imp/modules/rmf/dependency/RMF_source/include -I/System/Library/Frameworks/Python.framework/Headers -I/Users/riccardopellarin/imp-project/imp-230115/imp/swig -I/Users/riccardopellarin/imp-project/imp-230115/imp/modules/rmf/dependency/RMF_source/swig    --std=c++11 --std=c++11 -MMD -MT src/dependency/RMF/swig/CMakeFiles/_RMF.dir/RMFPYTHON_wrap.cxx.o -MF "src/dependency/RMF/swig/CMakeFiles/_RMF.dir/RMFPYTHON_wrap.cxx.o.d" -o src/dependency/RMF/swig/CMakeFiles/_RMF.dir/RMFPYTHON_wrap.cxx.o -c src/dependency/RMF/swig/RMFPYTHON_wrap.cxx
src/dependency/RMF/swig/RMFPYTHON_wrap.cxx:99141:41: error: no matching constructor for initialization of 'RMF::BufferHandle'
      result = (RMF::BufferHandle *)new RMF::BufferHandle(arg1);
                                        ^                 ~~~~
/Users/riccardopellarin/imp-project/imp-230115/imp/modules/rmf/dependency/RMF_source/include/RMF/BufferHandle.h:22:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const RMF::BufferHandle' for 1st argument
class BufferHandle : public BufferConstHandle {
      ^
/Users/riccardopellarin/imp-project/imp-230115/imp/modules/rmf/dependency/RMF_source/include/RMF/BufferHandle.h:22:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'RMF::BufferHandle' for 1st argument
class BufferHandle : public BufferConstHandle {
      ^
/Users/riccardopellarin/imp-project/imp-230115/imp/modules/rmf/dependency/RMF_source/include/RMF/BufferHandle.h:28:3: note: candidate constructor not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const std::vector<char>' for 1st argument
  BufferHandle(const std::vector<char> &st) : BufferConstHandle(st) {}
  ^
/Users/riccardopellarin/imp-project/imp-230115/imp/modules/rmf/dependency/RMF_source/include/RMF/BufferHandle.h:25:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  BufferHandle() : BufferConstHandle(std::vector<char>()) {}
  ^
1 error generated.

**Comment by Pellarin** [comment]
Needed to reset RMF library to an older commit

`git reset 8e6eadcdc9d6219c3004d767dd4e5b6720c95599 --hard`

**Comment by benmwebb** [comment]
Which Mac OS X version? Any unusual setup? We build on 10.6, 10.9 and 10.10 with packages from Homebrew with no issues.

**Comment by dbau** [comment]
Hi,

I have the exact same problem (Mac OS 10.7.5).

How can I revert to the commit reported by Riccardo? The mentioned git
reset command do not work for me.

Davide



On Fri, Jan 23, 2015 at 6:42 PM, Riccardo Pellarin <notifications@github.com

**Comment by Pellarin** [comment]
Mac OS 10.9.2
Homebrew packages:

swig: stable 3.0.1
hdf5: stable 1.8.13
Python 2.7.5

**Comment by Pellarin** [comment]
Davide, if you didn't do that, you have to `cd imp/modules/rmf/dependency/RMF_source` and type the git command above. It is an RMF commit, not an IMP one.

**Comment by dbau** [comment]
Thanks Riccardo!

No luck, though

These are my Homebrew packages:
swig: stable 3.0.2
hdf5: stable 1.8.13
Python 2.7.6

I will try to install the same Python and swig version versions as you.

Davide

**Comment by benmwebb** [comment]
Messing with the RMF revision is obviously not a fix, but a workaround. This doesn't look like a problem with your SWIG or HDF5 versions to me. The problem is that SWIG is generating a wrapper for BufferHandle(std::string) and there is no such constructor any more (after the git version Riccardo mentions it changed to BufferHandle(std::vector<char>)). It looks like an old wrapper left over from before a "git pull" to me. I would try a clean build first.

**Comment by Pellarin** [comment]
Yes, that's why I used that specific commit. In my case it is a clean build.

**Comment by benmwebb** [comment]
Well, maybe you can humor me and triple check that it is a clean build... because there is no constructor that takes std::string in current RMF, so the only way for SWIG to generate such a wrapper (if it's not left over from an old build) is to just dream it up... and I can't see any reason why it'd do that.

**Comment by Pellarin** [comment]
OK No prob! I'll try a new checkout and clean build

**Comment by benmwebb** [comment]
So what happened with the fresh checkout?

**Comment by Pellarin** [comment]
I still get the same error message
```
 [183/639] Swig source
/usr/local/include/RMF/BufferConstHandle.h:46: Warning 467: Overloaded method RMF::BufferConstHandle::BufferConstHandle(std::vector< char,std::allocator< char > > const &) not supported (no type checking rule for 'std::vector< char,std::allocator< char > > const &').
[191/639] Building CXX object src/dependency/RMF/swig/CMakeFiles/_RMF.dir/RMFPYTHON_wrap.cxx.o
FAILED: /usr/local/bin/mpicxx   -D_RMF_EXPORTS -w -w -O3 -DNDEBUG -fPIC -Iinclude -I/usr/local/include -Isrc/dependency/RMF/src -I/Users/riccardopellarin/imp-project/imp-130215/imp/modules/rmf/dependency/RMF_source/src -I/usr/local/Cellar/hdf5/1.8.13/include -Isrc/dependency/RMF/include -I/Users/riccardopellarin/imp-project/imp-130215/imp/modules/rmf/dependency/RMF_source/include -I/System/Library/Frameworks/Python.framework/Headers -I/Users/riccardopellarin/imp-project/imp-130215/imp/swig -I/Users/riccardopellarin/imp-project/imp-130215/imp/modules/rmf/dependency/RMF_source/swig    --std=c++11 --std=c++11 -MMD -MT src/dependency/RMF/swig/CMakeFiles/_RMF.dir/RMFPYTHON_wrap.cxx.o -MF "src/dependency/RMF/swig/CMakeFiles/_RMF.dir/RMFPYTHON_wrap.cxx.o.d" -o src/dependency/RMF/swig/CMakeFiles/_RMF.dir/RMFPYTHON_wrap.cxx.o -c src/dependency/RMF/swig/RMFPYTHON_wrap.cxx
src/dependency/RMF/swig/RMFPYTHON_wrap.cxx:99250:41: error: no matching constructor for initialization of 'RMF::BufferHandle'
      result = (RMF::BufferHandle *)new RMF::BufferHandle(arg1);
                                        ^                 ~~~~
/Users/riccardopellarin/imp-project/imp-130215/imp/modules/rmf/dependency/RMF_source/include/RMF/BufferHandle.h:22:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const RMF::BufferHandle' for 1st argument
class BufferHandle : public BufferConstHandle {
      ^
/Users/riccardopellarin/imp-project/imp-130215/imp/modules/rmf/dependency/RMF_source/include/RMF/BufferHandle.h:22:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'RMF::BufferHandle' for 1st argument
class BufferHandle : public BufferConstHandle {
      ^
/Users/riccardopellarin/imp-project/imp-130215/imp/modules/rmf/dependency/RMF_source/include/RMF/BufferHandle.h:28:3: note: candidate constructor not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'const std::vector<char>' for 1st argument
  BufferHandle(const std::vector<char> &st) : BufferConstHandle(st) {}
  ^
/Users/riccardopellarin/imp-project/imp-130215/imp/modules/rmf/dependency/RMF_source/include/RMF/BufferHandle.h:25:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  BufferHandle() : BufferConstHandle(std::vector<char>()) {}
  ^
1 error generated.
```

**Comment by benmwebb** [comment]
Hmm, is it possible that you (either of you) have a copy of RMF installed somewhere? (e.g. `/usr/local/include/RMF/`, `/usr/include/RMF/`) Possibly SWIG is picking those up in front of the ones in your IMP checkout. If so, try temporarily renaming the RMF include directory (so that SWIG can't find it) to see if that fixes the compile.

**Comment by benmwebb** [comment]
... or you could try updating to latest git HEAD - I tweaked the RMF include paths (see above commit).

**Comment by Pellarin** [comment]
Yes indeed, I had an IMP-2.3.1 binary installed on my mac, and that conflicted with the compilation. The latest commit solved the problem. We can close this issue for me, thanks.
