### ISSUE TITLE
Tidy up doc pages and website

### ISSUE THREAD

**Issue by benmwebb** [salilab/imp#868]
@cgreenberg @duhovka @procyon777 @saltzberg 

Make default "doc" page less developer-oriented; move things out of wiki into main docs; remove redundant or outdated docs; flesh out the "about" page; add more examples to the front page; add a link to the front page from doxygen docs; link to Sali lab from front page; remove left pane from doxygen docs.

Guys, please add anything I missed ;) And we may need to split this up into subissues if we get carried away.

**Comment by benmwebb** [comment]
Oh, and rename "applications" to "command line tools"

**Comment by benmwebb** [comment]
The existing tutorial and manual will be rearranged into a manual and reference guide as follows:

Manual:
 - includes what was previously called the "tutorial"
 - designed to be read sequentially
 - should be aimed mostly at "users"
 - organize by concept (e.g. multi-state; parallelization)
 - examples should be of biological interest (e.g. systems page, current tutorial examples)
 - link directly from main website
 - link to reference guide for more in-depth discussion (e.g. lists of all possible arguments for Python functions)
 - documentation should come from standalone `.dox` or `.md` files
 - can include introductions to programming concepts, e.g. "how to write a restraint in C++ or Python"

Reference guide:
 - includes most of what was previously called the "manual"
 - random access 
 - should be aimed mostly at "developers"
 - organize by module/class
 - examples should be of API usage (examples directories)
 - link only from the manual
 - documentation should come more or less exclusively from comments in C++ or Python files

**Comment by cgreenberg** [comment]
Sounds fantastic! Yeah, "manual" as a sequential document makes more sense. Also maybe a good idea to define user and developer somewhere, to define user expectations - that unless they're using a web server, probably some coding is needed.
