### ISSUE TITLE
pair score macro

### ISSUE THREAD

**Issue by yannickspill** [salilab/imp#874]
Where is `IMP_PAIR_SCORE_METHODS` defined?

**Comment by shruthivis** [comment]
In kernel/pair_macros.h in the build directory, not in the imp source
directory.

e.g. build/include/IMP/kernel/pair_macros.h

It is probably one of those macros that gets built by scripts instead of
being present in the source code.

**Comment by yannickspill** [comment]
Thanks!
bonus question: do you know what is the mechanism that generates this macro?

**Comment by shruthivis** [comment]
No, sorry. I'll have to skip the bonus!

**Comment by benmwebb** [comment]
`tools/build/make_containers.py`

**Comment by yannickspill** [comment]
thanks!
