### ISSUE TITLE
doc layout changed

### ISSUE THREAD

**Issue by yannickspill** [salilab/imp#875]
In the IMP docs, why did the two-column display change for a one-column? In particular, where did the "class examples" section go?

**Comment by benmwebb** [comment]
See issue #868.  Since nobody here uses the class examples, it clutters the page to have a link on every doc page. They are still linked from the main page as "Which examples each class is used in".

**Comment by yannickspill** [comment]
ok I understand. as long as you keep that page somewhere, I'm fine with it. It's just very convenient to know how to use a class by looking at examples imho.
