### ISSUE TITLE
Consider using git subtree rather than git submodule

### ISSUE THREAD

**Issue by benmwebb** [salilab/imp#876]
git submodule causes a couple of problems for us:

 - switching between master and develop branches can confuse git if submodules have moved between the two branches
 - github's tarballs for releases do not include contents of submodules (making them useless)

git subtree may be one way to avoid these problems - hopefully without introducing new ones.

**Comment by benmwebb** [comment]
Another submodule problem: since we use relative paths in `.gitmodules`, forks don't work (unless you change the paths or also fork the submodule repos). We can't use full paths in `.gitmodules` since that would force a protocol (git vs. https).

subtrees seem to have three downsides:
 - git commands to pull updates are more complicated
 - since the code is included into the repository, the repository size increases
 - need to be a bit more careful that repository commits and subtree commits do not overlap

**Comment by salilab-test** [comment]
As of 54b206e2e, no more submodules should exist in IMP.

**Comment by benmwebb** [comment]
Note also that `git worktree` does not work with submodules (but subtrees should be fine).
