### ISSUE TITLE
rmf_pdb fails

### ISSUE THREAD

**Issue by shruthivis** [salilab/imp#878]
Is the build/bin/rmf_pdb executable supposed to work? It fails for my RMF: prints out an empty PDB with 
MODEL   1
ENDMDL 

Example RMF is here /netapp/sali/shruthi/test.rmf

**Comment by benmwebb** [comment]
All the executables are supposed to work ;) But are you sure you don't mean `pdb_rmf`? It converts a PDB file into an RMF - since RMF is a superset of PDB the reverse transformation is generally not possible.

**Comment by shruthivis** [comment]
No I actually mean rmf_pdb: there is such an executable in build/bin for
me. I just wanted an easy way to get the xyzr's for all the beads in my
system, and was wondering if rmfs could be converted to pdb.

**Comment by benmwebb** [comment]
Ah, right - that's not in IMP, but in RMF. It only extracts the atoms from an RMF file, so if you only have beads, an empty PDB file is what you'll get.

**Comment by shruthivis** [comment]
Got it, thanks!

**Comment by benmwebb** [comment]
See also salilab/rmf#122.
