### ISSUE TITLE
deprecated random generator

### ISSUE THREAD

**Issue by yannickspill** [salilab/imp#880]
`core::MonteCarlo` uses `boost::uniform_real<>` when it should use `boost::random::uniform_real_distribution` or `uniform_01`, since the former is deprecated in recent boost distributions. Also it is unclear to me whether it is going to use the IMP random number generator or not some default one.

**Comment by benmwebb** [comment]
While it is deprecated in recent Boost versions, `uniform_real_distribution` isn't available in older Boosts (and we work with Boosts as old as 1.41) so we can't switch to that. I'm reluctant to switch to `uniform_01` unless there's a really compelling reason to do so (and given the [attitude of the Boost folks](http://lists.boost.org/Archives/boost/2004/12/78254.php) I'm not sure it's a good idea).

If you look in `src/MonteCarlo.cpp` you'll see that when the Boost object is actually used to generate a random number, it does use `base::random_number_generator` as its generator, so no worries there.

**Comment by yannickspill** [comment]
Bonus question: do you know if constructing/destructing these objects at each call, as is done in `NormalMover`, incurs any significant overhead? (as opposed to storing them somewhere)

**Comment by benmwebb** [comment]
Looking at the code, the constructors don't do anything except copy in a couple of variables, so I'd be enormously surprised if you saw any overhead.
