### ISSUE TITLE
IMP.em.SampledDensityMap

### ISSUE THREAD

**Issue by petercim** [salilab/imp#885]
Hi, did someone figure out why does this function sometimes cut the space of all solutions? For example, if I run it on an ensemble of models and then open the resulting mrc file in Chimera, I'll see a sharp edge, denoting that a region is missing. "volume region all" command in Chimera does not help ...

**Comment by benmwebb** [comment]
I've never seen the behavior you mention. I'll need to see an example.

**Comment by benmwebb** [comment]
Cannot reproduce without inputs, but may be related to #1036.
