### ISSUE TITLE
`Pointer.h` not found

### ISSUE THREAD

**Issue by yannickspill** [salilab/imp#889]
Compiling some code that didn't move for a while, in `isd2`. Now it breaks with the 2.4.0 so I guess I need to do some updating.
```
include/IMP/isd2/SAXSRestraintLN.h:16:25: fatal error: IMP/Pointer.h: No such file or directory
 #include <IMP/Pointer.h>
```
Where did these guys move?

of course, removing the offending line does not help:
```
In file included from /home/yannick/imp/src/modules/isd2/src/SAXSRestraintLN.cpp:9:0,
                 from src/isd2_all.cpp:1:
include/IMP/isd2/SAXSRestraintLN.h:128:3: error: ‘Pointer’ does not name a type
   Pointer<const saxs::Profile> exp_profile_;
   ^
```

thanks
Yannick

**Comment by benmwebb** [comment]
Nope, isd2 is tested and works fine with latest IMP, no updating needed: https://salilab.org/internal/imp/nightly/results/?p=build

IMP/Pointer.h didn't go anywhere. You should probably try a clean checkout - sounds like something is screwed up at your end.
