### ISSUE TITLE
Use per-particle locks for updating derivatives rather than critical section(?)

### ISSUE THREAD

**Issue by drussel** [salilab/imp#89]
omp_lock_t writelock;

OMP_INIT_LOCK(&writelock);
# pragma omp parallel for

for ( i = 0; i < x; i++ )
{
    // some stuff
    OMP_SET_LOCK(&writelock);
    // one thread at a time stuff
    OMP_UNSET_LOCK(&writelock);
    // some stuff
}

OMP_DESTROY_LOCK(&writelock);

**Comment by benmwebb** [comment]
Likely we won't do this, closing.
