### ISSUE TITLE
Remove VectorOfFloats/Doubles from Python

### ISSUE THREAD

**Issue by benmwebb** [salilab/imp#891]
They are kind of ugly, violate IMP standards, and don't behave like Python lists (users must use C++ methods to populate them). Either have the Python functions that take these types instead return a new type (at which point existing typemaps will convert it into a regular Python list) or have them take a numpy array. The latter would be more efficient (no copying involved).

**Comment by barakr** [comment]
I tried to avoid them and my main trouble, specifically for random numbers, is lack of ability to clearly distinguish doubles from floats. Probably just couldn't find the clean way to do it - happy for suggestions. In fact, I only wanted this in Python for the unit tests.



‫ב-10 במאי 2015, בשעה 09:48, ‏‏Ben Webb ‏<notifications@github.com> כתב/ה:‬

**Comment by barakr** [comment]
P.s. Floats in imp is actually doubles. Am I the only one finding this confusing? :) Can Floats be changed to Reals, perhaps, in some backward compatible way (eg, deprecate Floats)



‫ב-10 במאי 2015, בשעה 09:48, ‏‏Ben Webb ‏<notifications@github.com> כתב/ה:‬

**Comment by benmwebb** [comment]
> I tried to avoid them and my main trouble, specifically for random numbers, is lack of ability to clearly
> distinguish doubles from floats. Probably just couldn't find the clean way to do it - happy for 
> suggestions. In fact, I only wanted this in Python for the unit tests.

No problem - I'll handle this (this is why I assigned it to myself). It should be pretty straightforward.

**Comment by benmwebb** [comment]
> P.s. Floats in imp is actually doubles. Am I the only one finding this confusing? :)

`Float` is shorthand for "floating point particle attribute" so the name sounds fine to me (and it would certainly be a big hassle to change everywhere in a backwards-compatible way). It shouldn't be used anywhere outside of particle attributes (other IMP code explicitly takes `double`). The underlying C++ type is unimportant, so if you're worrying about whether it's `float` or `double`, you're doing it wrong. ;) It happens to be `double` because on a modern 64-bit system there's little reason to use `float`.

**Comment by barakr** [comment]
it takes twice as long to generate random doubles :)

On Mon, May 11, 2015 at 11:20 AM, Ben Webb <notifications@github.com> wrote:

> P.s. Floats in imp is actually doubles. Am I the only one finding this
> confusing? :)
>
> Float is shorthand for "floating point particle attribute" so the name
> sounds fine to me (and it would certainly be a big hassle to change
> everywhere in a backwards-compatible way). It shouldn't be used anywhere
> outside of particle attributes (other IMP code explicitly takes double).
> The underlying C++ type is unimportant, so if you're worrying about whether
> it's float or double, you're doing it wrong. ;) It happens to be double
> because on a modern 64-bit system there's little reason to use float.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/salilab/imp/issues/891#issuecomment-101005144>.
>



-- 
Barak

**Comment by benmwebb** [comment]
> it takes twice as long to generate random doubles :)

Well, if that's true (it surprises me), by all means do that part of the calculation using `float`. I expect simulations will survive without 18 decimal places of randomness anyway!
