### ISSUE TITLE
IMP::isd::CrossLinkMSRestraint must deal with residues assigned to the same particle

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#893]
in the latest imp commit 28b26c17830104e3e3d707f748d24f9aa586fba4 I've introduced a distance calculation when two residues are belonging to the same particle:

```
        double dist ;
        if (ppi[0] != ppi[1]) {
            core::XYZ d0(get_model(), ppi[0]), d1(get_model(), ppi[1]);
            dist =
            (d0.get_coordinates() - d1.get_coordinates()).get_magnitude();
        } else {
            // If the residues are assigned to the same particle-domain
            // get the distance as if the residues positions 
            // where randomly taken from the 
            // within the sphere representing the domain
            // Lund O, Protein Eng. 1997 Nov;10(11):1241-8.
            double R=core::XYZR(get_model(), ppi[0]).get_radius();
            dist=36.0/35.0*R;
        }
        if (dist<0.0001){dist=0.0001;}
```

Namely, if they belong to the same particle the distance of the residues is the mean distance calculated within the sphere.
As an extra check, I've added 

```
if (dist<0.0001){dist=0.0001;}
```

although in practice this should never happen

I've changed the test accordingly.

SJ, please check that your calculations are not dying now.

**Comment by procyon777** [comment]
Does it means that the distance between the XL pair is "center-to-center" distance?  I thought that you implemented the "surface-to-surface" distance before.

**Comment by procyon777** [comment]
We need to add the followings in the crosslinking.py of PMI too, for saving outputs correctly.

            if p0 != p1 :
                dist = IMP.core.get_distance(IMP.core.XYZ(p0), IMP.core.XYZ(p1))
            else :
                dist = 36.0/35.0*IMP.core.XYZR(p0).get_radius()
            if dist < 0.001: dist = 0.001

            output["ISDCrossLinkMS_Distance_" +
                   label + "_" + self.label] = str(dist)

I'm testing your changes right now, and will update you soon.

**Comment by Pellarin** [comment]
mmmmh, I prefer not to change that for the moment. The statistical distance between two residues is somewhat something different form the distance between two particles.

**Comment by Pellarin** [comment]
the "center-to-center" distance is used the statistical distance, and then the probability.

**Comment by Pellarin** [comment]
The latest imp and pmi commits close this issue

**Comment by Pellarin** [comment]
imp 458490fc1c8c04a82a728678eb7dd414ac9afb1a
pmi 9af128ca2d72341c579d33b6f78f20de4f937021
