### ISSUE TITLE
Need an easy way to get ALL resolutions for a Selection

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#900]
For example we often want to create a rigid body using all resolutions. Currently Selection lets you set a resolution and find the NEAREST resolution. But if you want them all then you need to either 1) keep track of what resolutions were set up and select each of them or 2) manually move up the hierarchy and call get_resolutions() on the Representation object. 

Not sure the solution here. Perhaps we can pass (yet another) keyword to Selection to optionally treats resolution like all other keywords (so that if you don't pass the resolution, it gives you all of them). Any other ideas?

**Comment by cgreenberg** [comment]
We also need this to get, for example, the IMP.atom.DENSITIES representation if we don't know the resolution. Currently if you request DENSITIES but pass the base resolution, you won't get the densities!

**Comment by cgreenberg** [comment]
@benmwebb any ideas? Currently if you want to expand a selection to all resolutions you have to do something like this:

```
rep = (search up tree to find Representation node)
for each resolution
   select with resolution
return combined results
```

**Comment by benmwebb** [comment]
Not sure if I understand you here, but Selection is specifically designed to give you a single-resolution "slice" through your system. It wouldn't make any sense to use it for multiple resolutions. And even if you could, it would basically have to do what your pseudocode does anyway.

**Comment by cgreenberg** [comment]
Added a python function that works like Selection but does some internal looping to find all resolutions.
5651d813ef96e6b868f7dbae5cec4317a82ccc63
