### ISSUE TITLE
Add StructureSourceType

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#902]
Primarily so we can easily select things when the whole system is properly tagged with StructureSource. 

Type ideas (I'm open to better names)

IMP.atom.XRAY, IMP.atom.MODEL, IMP.atom.EM, and something to represent beads with no previous structure, perhaps IMP.atom.ABINITIO or IMP.atom.NOSTRUCTURE or something

**Comment by saltzberg** [comment]
Cool.  I think that works.  Add NMR.  HOMOLOGY over MODEL?

ABINITIO and NOSTRUCT are different things, correct?  ABINITIO would be,
say, ideal_helix while NOSTRUCT would just be strings of beads?


On Wed, Jun 24, 2015 at 12:32 PM, Charles Greenberg <
notifications@github.com> wrote:

> Primarily so we can easily select things when the whole system is properly
> tagged with StructureSource.
>
> Type ideas (I'm open to better names)
>
> IMP.atom.XRAY, IMP.atom.MODEL, IMP.atom.EM, and something to represent
> beads with no previous structure, perhaps IMP.atom.ABINITIO or
> IMP.atom.NOSTRUCTURE or something
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/salilab/imp/issues/902>.
>



-- 


Daniel Saltzberg
Post-doctoral Scholar
University of California at San Francisco
Lab of Andrej Sali (www.salilab.org)

T: 415.514.4258

*Mailing Address:*
UCSF MC 2552,
Mission Bay, Byers Hall
1700 4th Street, Suite 503B
San Francisco, CA 94158-2330

saltzberg@salilab.org
ds229@bu.edu
