### ISSUE TITLE
python - how to delete hierarchies?

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#914]
I have a program reading many PDB files and storing coordinates. Memory is exploding. Is there something I should do besides calling `del hierarchy` each time I finish with a file?

**Comment by benmwebb** [comment]
Sure, `del hierarchy` will only delete the Python reference to the Hierarchy decorator - it won't delete the underlying Particle (or the child Particles). To do that, call `IMP.atom.destroy(hierarchy)`.

**Comment by cgreenberg** [comment]
Thanks for clarifying and adding that to the docs
