### ISSUE TITLE
IMP.core.Gaussian methods

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#917]
Why IMP.core.Gaussian.get_local_covariance() returns IMP_Eigen::Matrix3d, while IMP.core.Gaussian.set_local_covariance(const IMP_Eigen::Vector3d covar) ?

**Comment by Pellarin** [comment]
Also, would be nice to have method such as IMP.core.Gaussian(p).set_gaussian(algebra::Gaussian3D g) to set the attributes of a Gaussian without using set_local_covariance and set_global_covariance

**Comment by Pellarin** [comment]
My problem is that I want to copy the attributes of one gaussian to another... not clear hot to do that. This test returns an error:

```
import IMP
import IMP.core

m=IMP.Model()
p1=IMP.Particle(m)
g1=IMP.core.Gaussian.setup_particle(p1)
p2=IMP.Particle(m)
g2=IMP.core.Gaussian.setup_particle(p2)
gc=g2.get_global_covariance()
g1.set_global_covariance(gc)
```
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    g1.set_global_covariance(gc)
  File "/Bis/home/rpellari/imp-projects/imp-080915/imp-fast/lib/IMP/core/__init__.py", line 6908, in set_global_covariance
    return _IMP_core.Gaussian_set_global_covariance(self, *args)
TypeError: in method 'Gaussian_set_global_covariance', argument 2 of type 'IMP_Eigen::Matrix3d'
```

**Comment by cgreenberg** [comment]
Yes, I will add a set_gaussian function that will take a Gaussian3D (which you can get from another Gaussian particle with get_gaussian() )
