### ISSUE TITLE
rmf_show does not properly display Representations

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#919]
`rmf_show` is putting alternate representations next to the Representation particle, instead of underneath it.  Actually I get the same incorrect display in Chimera. However I think it's being *stored* correctly because I'm able to select things properly when I read it back in. Here is some sample code:
```python
import IMP
import IMP.rmf
import RMF

mdl = IMP.Model()
p1 = IMP.Particle(mdl)
x1 = IMP.core.XYZR.setup_particle(p1,
                                  IMP.algebra.Sphere3D(IMP.algebra.Vector3D(0,0,0),1))
IMP.atom.Mass.setup_particle(p1,1)
p1.set_name("res0")

p2 = IMP.Particle(mdl)
x2 = IMP.core.XYZR.setup_particle(p2,
                                  IMP.algebra.Sphere3D(IMP.algebra.Vector3D(0,0,0),1))
IMP.atom.Mass.setup_particle(p2,1)
p2.set_name("res1")

root = IMP.atom.Hierarchy.setup_particle(IMP.Particle(mdl))
root.set_name('root')
rep = IMP.atom.Representation.setup_particle(root,0)
rep.add_child(p1)
rep.add_representation(p2,IMP.atom.BALLS,1)

rh = RMF.create_rmf_file('test.rmf3')
IMP.rmf.add_hierarchy(rh, root)
IMP.rmf.save_frame(rh)
```
When you call `rmf_show` this is what you get:
```
IMP develop-9254314
 + "root" [root]
   + "root"[0] [representation]
     - "res0"[0] [representation]
   - "res1"[1] [representation]
```
Instead you should see "res1" underneath root.
```
IMP develop-9254314
 + "root" [root]
   + "root"[0] [representation]
     - "res0"[0] [representation]
     - "res1"[1] [representation]
```

**Comment by cgreenberg** [comment]
@benmwebb I'm not sure how to add a test for this. Probably getting it fixed here is a prerequisite for getting things working in Chimera. DENSITIES don't even display there.

**Comment by benmwebb** [comment]
The existing behavior looks correct to me. res1 *isn't* a child of root - it acts as a *replacement* for it (if you select resolution=1) so it's displayed at the same level as root in the hierarchy. res1 would normally be a Hierarchy particle though, in turn containing individual beads added with `add_child`. Those children would end up at the same level as your "res0" child.

**Comment by cgreenberg** [comment]
OK. Fine, that makes sense. Probably the solution to making things cleaner is to make the Representation (and its non-child resolutions) all the children of the Molecule (I was previously making the Molecule also the representation).
