### ISSUE TITLE
RMF doesn't let you repeat representations

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#920]
RMF won't allow using a particle multiple times in Representation. This is needed, for example, when you have particles that are also their own DENSITIES (e.g. for flexible beads or all-atom simulations) and you want them to be returned when you call:
`IMP.atom.Selection(hier,representation_type=IMP.atom.DENSITIES`

I added a test in de8f676355c139550639447547e2f4cb3bbacb55. The error is:
 `RuntimeError: UsageError: "Collision on association keys."`

**Comment by cgreenberg** [comment]
@benmwebb Does this look fixable? To get around it I'd have to have two particles for each flexible bead - one for the bead, one for the density. Alternatively one could special-case Selection to return the original particle if it's decorated as a Gaussian.

**Comment by benmwebb** [comment]
No idea, sorry. It'll take a while to dig in the RMF code for it, and there are lots of other bugs that I need to get to first!

**Comment by cgreenberg** [comment]
COOL! Now if we can just get it to work in Chimera... 👌
