### ISSUE TITLE
Request of features in isd.gmm_tools.py

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#921]
@cgreenberg 

This patch might be useful. 1) have  min_covar defined so that we don't have blade- and pencil-shaped gaussians (eg. min_covar=2)   2) having the akaike score returned can be useful to compare different GMMs

```
diff --git a/modules/isd/pyext/src/gmm_tools.py b/modules/isd/pyext/src/gmm_tools.py
index 84c8f77..4256ade 100644
--- a/modules/isd/pyext/src/gmm_tools.py
+++ b/modules/isd/pyext/src/gmm_tools.py
@@ -227,7 +227,8 @@ def fit_gmm_to_points(points,
                       init_centers=[],
                       force_radii=-1.0,
                       force_weight=-1.0,
-                      mass_multiplier=1.0):
+                      mass_multiplier=1.0,
+                      min_covar=0.0,
+                      akaikescore=None):
     '''fit a GMM to some points. Will return core::Gaussians.
     if no particles are provided, they will be created
 
@@ -267,6 +268,7 @@ def fit_gmm_to_points(points,
                           n_iter=num_iter,
                           covariance_type=covariance_type,
                           params=params,
+                          min_covar=min_covar,
                           init_params=init_params)
 
     if force_weight!=-1.0:
@@ -276,7 +278,10 @@ def fit_gmm_to_points(points,
     if init_centers!=[]:
         gmm.means_=init_centers
     print('fitting')
-    gmm.fit(points)
+    model=gmm.fit(points)
+    
+    if akaikescore is not None:
+        akaikescore.append(model.aic(points))
 
     print('>>> GMM score',gmm.score(points))
 
```

**Comment by Pellarin** [comment]
Of course, the variable `akaikescore` should be a list to return a value in.

**Comment by cgreenberg** [comment]
Looks good to me! I'd just make a few changes. First, don't use that return technique, it's weird. I'd just have `fit_gmm_to_points()` return the tuple `(gmm.score(points), akaikescore)`. That shouldn't break anything. Then just add to the documentation an explanation that `akaikescore` is a parsimony measure (right?).

**Comment by Pellarin** [comment]
Great! good idea to return the tuple. 

A possible documentation for the `akaikescore` parameter:

Akaike information criterion for the current model fit. It is a measure of the relative quality of the GMM that takes into account the parsimony and the goodness of the fit.

**Comment by Pellarin** [comment]
929715a0bcb9a6ce84eca1e115ce984f67b14d0c close it
