### ISSUE TITLE
How can a restraint cache stuff?

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#924]
Asking here because maybe the answer can go in the docs somewhere. I am working on a new restraint that, in addition to the model particles to be restrained, takes an `isd::Scale` particle which contains a "nuisance" parameter that might only occasionally be updated (or never). I want to support caching of some large internal matrices that are very expensive to compute, but must be recomputed every time the Scale changes. What's the simplest way to do this?

A few things I know:
* This isn't obviously supported because `core::Restraint::unprotected_evaluate` is declared `const` and so cannot modify anything.
* I know that for the `isd::GaussianEMRestraint` we have something similar, where we cache the covariance matrices of each particle using `Model::add_cache_attribute()`. If the particles rotate then...somewhere (I cant remember) we call `core::Gaussian::update_global_covariance()`  But this is logical because those matrices are inherent to the particle. For my problem, they are basically internal to the restraint and have no real meaning.

What's the solution here?

**Comment by benmwebb** [comment]
You could store it in the Restraint in a `mutable` attribute. Cached stuff is one acceptable use of `mutable`.

**Comment by cgreenberg** [comment]
Would a ScoreState also work? I'm not sure the use cases for them.

**Comment by benmwebb** [comment]
No, a ScoreState is for something that gets called every time the score is calculated. This is usually used to maintain invariants like rigid bodies and other constraints.

**Comment by cgreenberg** [comment]
What if I want to keep a cached `em::SampledDensityMap`? In the header I've declared:
```C++
mutable Float prev_resolution_; 
mutable em::SampledDensityMap * smap_; 
```
But in `unprotected_evaluate` I try to change the resolution:
```C++
  if (cur_resolution!=prev_resolution_){
    smap_->get_header()->set_resolution(cur_resolution)
    prev_resolution_ = cur_resolution;
}
```
I get this compilation error: `member function 'set_resolution' not viable: 'this' argument has type 'const IMP::em::DensityHeader', but function is not marked const
    smap_->get_header()->set_resolution(cur_resolution)`

Any ideas? My C++ knowledge is failing here...

**Comment by benmwebb** [comment]
I think you meant to call `get_header_writable()` rather than `get_header()`.
