### ISSUE TITLE
Deprecate atom::Hierarchy::get_as_xxx() methods

### ISSUE THREAD

**Issue by benmwebb** [salilab/imp#932]
For example, `h.get_as_residue()` returns a `Residue` decorator for a given `Hierarchy`, `h`. If `h` is not a residue, it returns an invalid decorator (default constructed).

Default-constructed decorators don't play very nicely with Python (e.g. pretty much anything other than calling their `get_is_valid()` method, even just printing them, will cause a segfault). And `get_as_residue()` does basically the same thing as the usual decorator access pattern, i.e.

    if IMP.atom.Residue.get_is_setup(h):
        r = IMP.atom.Residue(h)

... so there's really no reason to have a separate mechanism to get decorators here.

**Comment by cgreenberg** [comment]
get_as_xxx() is used in Hierarchy::show(), what will be the replacement?

**Comment by benmwebb** [comment]
Rather than the current

    if (get_as_atom()) {
      out << get_as_atom() << delimiter;
    }

we'd use

    if (Atom::get_is_setup(get_particle()) {
      out << Atom(get_particle()) << delimiter;
    }

This would make it consistent with normal decorator usage. And such usage is even used in that same function (for `Copy`, `RigidBody`).
