### ISSUE TITLE
Allow IMP::atom::get_next_residue and IMP::atom::get_previous_residue to consider PMI hierarchy structures

### ISSUE THREAD

**Issue by sethaxen** [salilab/imp#933]
Anything that IMP::atom::get_phi_dihedral_atoms and IMP::atom::get_psi_dihedral_atoms, including IMP::rotamer::RotamerCalculator, uses the IMP::atom::get_previous_residue and IMP::atom::get_next_residue. These require that the residue's parent be a Chain as the simple case. However, this results in residues built with PMI being unusable with these methods, as their hierarchical structure is Residue<-Fragment<-Fragment<-Chain. It would be nice if these methods considered the structure PMI generates.

**Comment by sdaxen** [comment]
I guess an alternative is for PMI to also setup the Fragments containing atomic residues as Chains. Not certain if this is proper or not.

**Comment by benmwebb** [comment]
Yes, those functions are pretty simplistic, but it wouldn't be difficult to handle intervening Fragments. Pretty sure that making a particle both a Fragment and a Chain would result in an invalid hierarchy though.

**Comment by sdaxen** [comment]
I actually tried setting up one of the Fragments generated by PMI as a Chain, and that worked. Not sure if it breaks any other PMI assumptions.

**Comment by benmwebb** [comment]
There's nothing to stop you decorating any particle any way you like, but in a valid `Hierarchy` each node can only be of one type. `Hierarchy::get_is_valid()` is supposed to check for that, but looking at the code it looks like it misses the specific case of a node being both `Fragment` and `Chain`.

**Comment by cgreenberg** [comment]
PMI structure is Root ("System") > State > Molecule/Chain > Fragment/Representation > [Residue > Atom] OR [Beads] OR [Densities]

So you can't change the fragments to chains or else you'll have nested chains
