### ISSUE TITLE
 No module named isd2

### ISSUE THREAD

**Issue by atfrank** [salilab/imp#941]
Obtained the  "No module named isd2" when trying to use the saxs restraint in PMI. I tried searching the IMP repo for isd2 but could not find it.

**Comment by benmwebb** [comment]
@cgreenberg would know more, but it looks like the SAXS restraint in PMI isn't fully functional yet, at least in a Bayesian sense (isd2 is the not-yet-released development version of the isd module).

**Comment by saltzberg** [comment]
I'll implement a basic SAXS restraint (wrapper of IMP.saxs.Restraint) that you can use with PMI.

**Comment by atfrank** [comment]
@saltzberg: thanks.

**Comment by saltzberg** [comment]
Ok, to set up the SAXS restraint:
``
saxs_rest = IMP.pmi.restraints.saxs.SAXSRestraint(pmi_molecule, 'saxs_file.dat')
``

You can then add it to the scoring function using the standard syntax:
``
saxs_rest.add_to_model()
``

Keeping this issue open since we still need to modify isd to implement Bayesian SAXS (or decide that we will not support it).

**Comment by atfrank** [comment]
@saltzberg: I should pull the develop branch — correct?

**Comment by saltzberg** [comment]
@atfrank Yes.  You'll need to pull from the PMI develop branch.  If you've been using the PMI included in the IMP repository, just delete your imp/modules/pmi folder and clone PMI into the same place then rebuild IMP.

**Comment by yannickspill** [comment]
Hi

I'm the author of the isd2 saxs restraint. Conceptually, the restraint
is ready, I think it's also working, but I needed to check it first as
it's been a long time. The paper is almost written but as I'm doing my
new post-doc I didn't have the time for it lately. Please don't modify
the isd2 restraint, I'll do it myself if you don't mind.

thanks

Yannick
