### ISSUE TITLE
When passed a PMI hierarchy, terminus selection returns multiple atoms

### ISSUE THREAD

**Issue by sdaxen** [salilab/imp#949]
When passed a hierarchy created with PMI (simple reading of coordinates from PDB), IMP.atom.Selection(hier, terminus=IMP.atom.Selection.N).get_particles() returns the nitrogens from all residues rather than just from the first residue.

**Comment by cgreenberg** [comment]
I didn't even know about `terminus=IMP.atom.Selection.N`. Cool! Anyway looks like it isn't playing well with Fragments. I'll add a test.

**Comment by cgreenberg** [comment]
@sdaxen can you verify it's working ok for PMI hierarchies? there could be additional problems with Representations
