### ISSUE TITLE
Can we have min_covar as option in isd/create_gmm.py ?

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#950]
@cgreenberg I can do it, if you don't have anything against.

**Comment by benmwebb** [comment]
Do you still need this? If not, I'll close this issue. Note that scikit-learn 0.20 will drop the `GMM` class entirely anyway. The replacement `GaussianMixture` class doesn't support `min_covar` (there is a `reg_covar` argument but it appears to behave differently).

**Comment by Pellarin** [comment]
yes, close

Riccardo Pellarin, PhD
===================
Institut Pasteur
CNRS UMR 3528
25, rue du Docteur Roux
75724 Paris Cedex 15, France
riccardo.pellarin@pasteur.fr
+33 (0)1 44 38 93 63
