### ISSUE TITLE
No rule to make target IMP-version

### ISSUE THREAD

**Issue by huge200890** [salilab/imp#956]
Hi,
I tried ' make ' after cmake following installation guide, but  I always got error as: 
 
[ 10%] Built target IMP-version
Scanning dependencies of target IMP.algebra-version
make[2]: *** No rule to make target `IMP-version', needed by `lib/IMP/algebra/_version_check.py'.  Stop.
make[1]: *** [modules/algebra/CMakeFiles/IMP.algebra-version.dir/all] Error 2
make: *** [all] Error 2

Does anyone can help me solve this problem? 

Thanks so much for your time,
jie

**Comment by benmwebb** [comment]
What operating system, version of cmake, version of IMP, and what are the actual commands you're running to unpack IMP, run cmake, and run make?

**Comment by huge200890** [comment]
Dear benmwebb ,
Thanks for quick reply. 
(1) operating system: I am using Red Hat 4.4.7-4
(2) version of cmake: The cmake version I used is cmake-2.8.3
(3) The installation step I did is: 
        a. git clone https://github.com/salilab/imp.git
        b. mkdir IMP_tools
        c. cmake-2.8.3/bin/cmake ../imp/ -DCMAKE_INSTALL_PREFIX=./ -DCMAKE_BUILD_TYPE=Release
        d. make -j 8

Then I got error as I showed above.
make[2]: *** No rule to make target `IMP-version', needed by `lib/IMP/_version_check.py'.  Stop.
make[1]: *** [modules/kernel/CMakeFiles/IMP.kernel-version.dir/all] Error 2
make: *** [all] Error 2

PS: I have also installed several required tools, like hdf5-1.8.16, boost_1_59, python (version 2.6.6) 

Thanks,
Jie

**Comment by benmwebb** [comment]
There is no such thing as "Red Hat 4.4.7-4" (maybe you mean the gcc version). What is the content of `/etc/redhat-release`?

**Comment by huge200890** [comment]
Sorry, my mistake, the system version is Red Hat Enterprise Linux Server release 6.5 (Santiago)

And the gcc version I used is gcc version 4.4.7 20120313 (Red Hat 4.4.7-4)

Thanks.

**Comment by benmwebb** [comment]
Oh, in that case you'll need to ask your sysadmin to update it to RHEL 6.8. RHEL 6.5 has been obsolete since 2014, and RedHat doesn't support it any more. So we won't be able to reproduce your problem anyway. If it continues with RHEL 6.8, let us know.

**Comment by huge200890** [comment]
Dear benmwebb ,
Sure, I got it. Thanks, and one more question, 
I am trying to call IMP C++ library in my c++ program, can I directly copy all C++ library which are saved in 'include/IMP' and 'include/IMP.h' after cmake to my local c++ main directory, and use command like  "#include "IMP/IMP.h" to apply functions as IMP? 

Actually, I have already done this since I got trouble installing it, where I copied all header files and changed the path to each header file like '#include "<path>/header.h"', however, when I compiled the example program (https://integrativemodeling.org/1.0/tutorial/library.html),  it looks like I can't call namespace "IMP::" directly, for example, I got error like 

CMakeFiles/imp_test.dir/imp_test.cpp.o: In function `main':
imp_test.cpp:(.text+0x24e): undefined reference to `IMP::Model::Model(std::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
imp_test.cpp:(.text+0x277): undefined reference to `IMP::Particle::Particle(IMP::Model*)'
imp_test.cpp:(.text+0x2ac): undefined reference to `IMP::Particle::Particle(IMP::Model*)'
imp_test.cpp:(.text+0x2e8): undefined reference to `IMP::Particle::get_index() const'
imp_test.cpp:(.text+0x313): undefined reference to `IMP::Object::unref() const'
imp_test.cpp:(.text+0x332): undefined reference to `IMP::Particle::get_index() const'
imp_test.cpp:(.text+0x35d): undefined reference to `IMP::Object::unref() const'
imp_test.cpp:(.text+0x4a8): undefined reference to `IMP::core::XYZ::show(std::basic_ostream<char, std::char_traits<char> >&) const'
imp_test.cpp:(.text+0x4c5): undefined reference to `IMP::core::XYZ::show(std::basic_ostream<char, std::char_traits<char> >&) const'
imp_test.cpp:(.text+0x544): undefined reference to `IMP::Object::unref() const'
imp_test.cpp:(.text+0x562): undefined reference to `IMP::Object::unref() const'
imp_test.cpp:(.text+0x56f): undefined reference to `IMP::Object::unref() const'
imp_test.cpp:(.text+0x5f6): undefined reference to `IMP::Object::unref() const'


So does this mean I should not use C++ library in IMP directly?
Thanks

**Comment by benmwebb** [comment]
> can I directly copy all C++ library which are saved in 'include/IMP' and 'include/IMP.h' after cmake to my local c++ main directory

Just add the IMP include directory to your compiler search path with `-I`. No need to copy anything.

> it looks like I can't call namespace "IMP::" directly

The errors you show are linker errors, so most likely you forgot to add the IMP library directory to your linker search path with `-L` and to link to the libraries themselves with `-limp_kernel -limp_core` (and possibly other modules if you used them).

**Comment by huge200890** [comment]
Dear denmwebb,
Thanks so much, you made me much clear what I should do, I will try what you suggested, and hope it work.

Really appreciate your help,
Have a nice day,
Jie

**Comment by huge200890** [comment]
Dear denmwebb,
I tried to add -I<include path> to gcc compiler, it looks fine. 

About linking to library by using -L, could you let me know which IMP library directory I should use? How to use -limp_kernel and -limp_core to link the libraries?  

Thanks for your patience,
Best.

**Comment by benmwebb** [comment]
> About linking to library by using -L, could you let me know which IMP library directory I should use?

Well, the one containing the IMP libraries, of course. There's only one such directory. It'll contain `libimp_kernel.so`, `libimp_core.so` and so on.

> How to use -limp_kernel and -limp_core

Just literally add `-limp_kernel -limp_core` to your linker invocation.

If you further questions unrelated to this issue, the mailing list is the place to ask them.
