### ISSUE TITLE
(sovled) undesired Foxs program after compilation

### ISSUE THREAD

**Issue by huge200890** [salilab/imp#957]
Dear developers,

I tried to compile IMP packages(imp-2.6.2.tar.gz) from source code, the whole installation looks smoothly. However, after everything is done, I ran ./bin/foxs  native.pdb native.pdb.dat, I got some output info with warning like

./bin/foxs native.pdb native.pdb.dat 
1583 atoms were read from PDB file 
WARNING  Oxygen atom not found, using default O form factor for "OT1" "LYS"
WARNING  Oxygen atom not found, using default O form factor for "OT2" "LYS"
begin read_pdb:
  WARNING  Sorry, unable to read atoms from PDB file. Thanks for the effort.
end read_pdb
read_SAXS_file: native.pdb.dat size= 501 delta= 0.001 min_q= 0 max_q= 0.5
Profile read from file native.pdb.dat size = 501
Computing profile for native.pdb 1583 atoms 
start real partial profile calculation for 1583 particles 
/native.pdb native.pdb.dat Chi = 3.80143 c1 = 0.95 c2 = 0.0371201 default chi = 9.03969

**(the whole procedure  took around 20s)**

However, if I ran the foxs program downloaded directly from foxs server https://modbase.compbio.ucsf.edu/foxs/, it runs smoothly,

FoXS/foxs native.pdb native.pdb.dat 
1583 atoms were read from PDB file native.pdb
Profile read from file native.pdb.dat size = 501
Computing profile for native.pdb 1583 atoms 
native.pdb native.pdb.dat Chi = 3.80142 c1 = 0.95 c2 = 0.0371201 default chi = 9.03969

**(the whole procedure  took around 1s)**

So I am curious why my compiled program report some warning  and the running speed is much different? Is there any idea I can speed up my compiled program?

The following is my system information I used to compile IMP
1). Operating system:  Red Hat Enterprise Linux Server release 6.5 (Santiago)
2) gcc version: gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) 
3) boost version: 1.55.0
4) cmake: 3.4.1
5) The command I used is:  cmake ../imp-2.6.2/  -DCMAKE_INSTALL_PREFIX=/home/jh7x3/Mocapy_tool/IMP2.6.2/

Thanks so much for your help,
 Jie

**Comment by huge200890** [comment]
Dear Developer,

Sorry for the last question, it looks like I figured it out by adding the optional tools (ex. gsl-2.1,fftw-3.3.4,cgal,gsl), and the speed now is comparable to that the foxs server provide( I guess cgal works most for speed up, I need verify it). About the warning information, I have already understood how it works. 

Thanks again for all your contribution,
best

**Comment by Angrybird1997** [comment]
I have the same issue, but somehow in the end we can still get a 'right' result.
