### ISSUE TITLE
How to compile IMP with static library

### ISSUE THREAD

**Issue by huge200890** [salilab/imp#958]
Dear Developers,

I tried to compile IMP2.6.2  with static library by setting as  IMP_STATIC to ON instead of OFF in line 82 in CmakeLists.txt: 

set(IMP_STATIC off CACHE BOOL "Link all binaries and libraries statically; currently only supported on Linux systems with gcc.")

The cmake works smoothly without throwing error, but when I tried make, I got following error messages: 

Scanning dependencies of target IMP.kernel-doc
make[2]: *** No rule to make target `/home/imp-2.6.2/modules/kernel/IMP.kernel-python', needed by `doxygen/kernel/tags'.  Stop.
make[1]: *** [modules/kernel/CMakeFiles/IMP.kernel-doc.dir/all] Error 2
make: *** [all] Error 2

Could you help guide me how to set up static library for IMP to compile? 

Thanks so much,

**Comment by benmwebb** [comment]
> I tried to compile IMP2.6.2 with static library

That will probably work, but we really don't recommend it. Static libraries are much more difficult to work with than dynamic libraries, and you'll find that large parts of IMP simply won't build (for example, none of the Python wrappers will work).

> by setting as IMP_STATIC to ON instead of OFF in line 82 in CmakeLists.txt: 

To set cmake variables, either use `ccmake` or add them to your `cmake` invocation, e.g. `cmake -DIMP_STATIC=ON`. Editing `CMakeLists.txt` is usually a very bad idea.

>  `make[2]: *** No rule to make target /home/imp-2.6.2/modules/kernel/IMP.kernel-python', needed bydoxygen/kernel/tags'. Stop.`

Hmm, that looks like a bug in our build system. I'll fix that. The easiest workaround for 2.6.2 would be to disable building the docs (it fails because these need the Python wrappers, which aren't there in static builds). Just add `-DIMP_DOXYGEN_FOUND=""` to your `cmake` invocation.

**Comment by huge200890** [comment]
Dear Developers,

Thanks for quick reply. I added -DIMP_STATIC=ON and disable the doxygen, the compilation starts until get such error：
[ 17%] Linking CXX executable kernel/test_cache
/usr/bin/ld: cannot find -lm
collect2: ld returned 1 exit status
make[2]: *** [modules/kernel/test/kernel/test_cache] Error 1
make[1]: *** [modules/kernel/test/CMakeFiles/IMP.kernel-test_cache.cpp.dir/all] Error 2

Do you have idea with this?  
Really appreciate your help,
Best

**Comment by benmwebb** [comment]
>  /usr/bin/ld: cannot find -lm

Well sure, for a static build, you'll need static libraries. libm is just one of them.

**Comment by huge200890** [comment]
Thanks,  now I make sense, and I should provide static library path and this problem was fixed by providing static library path of libm.a . 
And the whole installation procedure works smoothly now, and I can found static libraries lib/*a has been generated. 

However, if I add the path of CGAL, and compile again, I got library error 
Scanning dependencies of target IMP.algebra-lib
make[2]: *** No rule to make target `/home/jh7x3/Mocapy_tool/mpfr-2.4.2/lib/libmpfr.so', needed by `modules/cgal/test/cgal/test_bad_sav'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object modules/cgal/test/CMakeFiles/IMP.cgal-test_bad_sav.cpp.dir/test_bad_sav.cpp.o
[ 26%] Building CXX object modules/algebra/src/CMakeFiles/IMP.algebra-lib.dir/__/__/__/src/algebra_config.cpp.o
[ 26%] Building CXX object modules/algebra/src/CMakeFiles/IMP.algebra-lib.dir/__/__/__/src/algebra_all.cpp.o
make[2]: *** No rule to make target `/home/jh7x3/Mocapy_tool/mpfr-2.4.2/lib/libmpfr.so', needed by `modules/cgal/test/cgal/test_memory_problem'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object modules/cgal/test/CMakeFiles/IMP.cgal-test_memory_problem.cpp.dir/test_memory_problem.cpp.o
make[2]: *** No rule to make target `/home/mpfr-2.4.2/lib/libmpfr.so', needed by `modules/cgal/test/cgal/test_skin_failure'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 27%] Building CXX object modules/cgal/test/CMakeFiles/IMP.cgal-test_skin_failure.cpp.dir/test_skin_failure.cpp.o
make[1]: *** [modules/cgal/test/CMakeFiles/IMP.cgal-test_bad_sav.cpp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [modules/cgal/test/CMakeFiles/IMP.cgal-test_memory_problem.cpp.dir/all] Error 2
make[1]: *** [modules/cgal/test/CMakeFiles/IMP.cgal-test_skin_failure.cpp.dir/all] Error 2
[ 28%] Linking CXX static library ../../../lib/libimp_algebra.a 

Since I have also compiled mpfr as static library and only /home/mpfr-2.4.2/lib/libmpfr.a exists instead of /home/mpfr-2.4.2/lib/libmpfr.so,  can we also let IMP.cgal know we should access static library libmpfr.a instead of libmpfr.so during compilation? 

Thanks.

**Comment by huge200890** [comment]
Thanks, now I can success to get static library. And it works.
