### ISSUE TITLE
Broken webpage link in documentation

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#961]
In https://integrativemodeling.org/2.6.2/doc/manual/profiling.html the link to http://google-perftools.googlecode.com/svn/trunk/doc/heap_checker.html is broken

**Comment by Pellarin** [comment]
Maybe http://goog-perftools.sourceforge.net/doc/heap_checker.html ?

**Comment by benmwebb** [comment]
Already fixed in eb9e6e6fc.
