### ISSUE TITLE
Add ability to use multiple temperatures in MonteCarlo

### ISSUE THREAD

**Issue by sdaxen** [salilab/imp#986]
Currently, `IMP.core.MonteCarlo` permits one to set a single temperature which is used for all components of the scoring function. However, it can be very useful to set different temperatures for different groups of scoring terms. For example, in Bayesian modeling, varying the temperature for likelihood but not priors during replica exchange enables estimation of the density of states, which can be used to compute many ensemble properties (e.g., see [this paper](http://proceedings.mlr.press/v22/habeck12.html)).

**Comment by Pellarin** [comment]
> For example, in Bayesian modeling, varying the temperature for likelihood
but not priors

It is not something that need to be implemented in IMP.core.Montecarlo.
Varying temperature for the likelihood only corresponds to modulating the
weights of the corresponding
score terms. That has to be implemented in the ReplicaExchange, it is
called Hamiltonian Replica Exchange.


Riccardo Pellarin, PhD
===================
Institut Pasteur
CNRS UMR 3528
25, rue du Docteur Roux
75724 Paris Cedex 15, France
riccardo.pellarin@pasteur.fr
+33 (0)1 44 38 93 63

**Comment by sdaxen** [comment]
Thanks, @Pellarin, that's a good point I hadn't thought of. The only thing that's missing is for PMI Restraints to be aware of which `RestraintSet`s they return consist of likelihoods and which consist of priors. I'll create a separate issue for that.
