### ISSUE TITLE
Installation of imp2.8.0 source code

### ISSUE THREAD

**Issue by vas2201** [salilab/imp#989]
Hello IMP users.
I tried to install imp 2.8.0 as per given instructions in below web page on mac. 
https://integrativemodeling.org/2.8.0/doc/manual/installation.html

I am getting following error, could you please instruct me needful.

Thanking you !

srinivas@tmp002500ee0565%cmake /opt/local/NMR/imp 
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Running check_common_problems
-- Running clean_build_dir
-- Running setup_cmake
CMake Error at modules/rmf/dependency/RMF/cmake_modules/IMPExecuteProcess.cmake:59 (message):
   Failed to run COMMAND;/opt/local/NMR/imp/tools/build/setup_cmake.py: 1; Traceback (most recent call last):
    File "/opt/local/NMR/imp/tools/build/setup_cmake.py", line 244, in <module>
      main()
    File "/opt/local/NMR/imp/tools/build/setup_cmake.py", line 235, in main
      ordered = tools.compute_sorted_order(".", "")
    File "/opt/local/NMR/imp/tools/build/tools/__init__.py", line 479, in compute_sorted_order
      info = get_module_info(m, extra_data_path)
    File "/opt/local/NMR/imp/tools/build/tools/__init__.py", line 392, in get_module_info
      exec(open(df, "r").read(), d)

  IOError: [Errno 2] No such file or directory: './data/build_info/IMP.base'

Call Stack (most recent call first):
  modules/rmf/dependency/RMF/cmake_modules/IMPExecuteProcess.cmake:71 (imp_get_process_output)
  CMakeLists.txt:53 (imp_execute_process)

-- Configuring incomplete, errors occurred!
See also "/opt/local/NMR/imp/imp_release/CMakeFiles/CMakeOutput.log".
srinivas@tmp002500ee0565%

**Comment by benmwebb** [comment]
IMP 2.8.0 doesn't contain the IMP.base module - it was removed a long time ago - so my guess is you have mixed up your IMP 2.8.0 build with a previous one (maybe the 2.3.0 build you were trying earlier). Try a fresh build from scratch after deleting the `/opt/local/NMR/imp` directory.

**Comment by benmwebb** [comment]
Seeing no further comments here, I'm going to assume this fixed your problem. Reopen if it didn't.
