### ISSUE TITLE
Proposal: replace Python optparse usage with argparse

### ISSUE THREAD

**Issue by benmwebb** [salilab/imp#991]
For argument parsing, we currently use the Python `optparse` module. This has been deprecated and replaced with the more capable `argparse` module. Unfortunately, we still support Python 2.6 which only has `optparse`.

Currently in some places we have two code paths, one that uses `optparse` and the other that uses `argparse`. This makes maintaining the code awkward. In other places we just use `optparse` since, while it's deprecated, it hasn't been removed from Python 3 yet.

Proposal: use `argparse` everywhere. This will give nicer command line usage and allow us to drop the `optparse` code path. The downside is that the code won't work in vanilla Python 2.6. However, `argparse` is available as a third-party package for Python 2.6 and is widely available (e.g. RHEL 6, which is probably the only place where Python 2.6 is still being used, includes a `python-argparse` package, which we can simply add as a prerequisite for the IMP package).

**Comment by benmwebb** [comment]
Note that the Windows installer still supports Python 2.6 (although perhaps we should simply drop that) and the Mac installer works with OS X as old as 10.6, which ships with Python 2.6 (perhaps we could raise the minimum OS X version to 10.8, which has Python 2.7). Possibly we could bundle `argparse.py` with these installers (it is pretty small).

**Comment by hugovk** [comment]
I would use argparse everywhere **and** (before that) drop Python 2.6: it's 4 years without a security release, it's little used, many other important Python libraries have also dropped it, RHEL 6 can upgrade Python using SCL or pin to the last 2.6 release, and add you've discovered, the maintenance burden is a hassle. 

(It's also time to start planning on dropping 2.7.  https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst)
