### ISSUE TITLE
Store polymer type in IMP.atom.Chain and RMF-related objects.

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#992]
related to #965. It helps interpreting correctly the one-letter sequence. Suggested keys are "Protein", "DNA", and "RNA".

**Comment by benmwebb** [comment]
See also the polymer types accepted by PDB, which seems pretty comprehensive to me:
http://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_entity_poly.type.html

**Comment by Pellarin** [comment]
OK! Thanks!
